[package]
name = "day5_supply_stacks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "shared_lib"
path="src/lib/shared_lib.rs"

[dependencies]
